---
sidebar: sidebar 
permalink: concept-compute.html 
keywords: concepts, how cloud analyzer works, compute, compute costs, compute savings 
summary: BlueXPでは、SpotのCloud Analyzer サービスを活用することで、クラウドコンピューティング関連のコストを高度に分析し、コスト削減の可能性を特定することができます。 
---
= BlueXPのクラウド運用についてご紹介します
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
を活用して https://spot.io/products/cloud-analyzer/["SPOT の Cloud Analyzer サービス"^]BlueXPでは、クラウドコンピューティング関連のコストを高レベルで分析し、コスト削減の可能性を特定することができます。

Cloud Analyzer は、高度な分析を使用してクラウドコストを可視化し、分析するクラウドインフラ管理ソリューションです。このスライドでは、コストを最適化できる領域を示し、Spotの継続的最適化製品ポートフォリオを使用して数回のクリックで最適化を実装できます。



== の機能

* 月の現在のコスト、月あたりの予測コスト、および節約損失を表示するコスト分析
* 推定される追加の削減額を含む、アカウント別の支出効率のビュー
* 詳細については、スポットの Cloud Analyzer へのリンクを参照してください すべてのアカウントの支出について




== サポートされているクラウドプロバイダ

このサービスは AWS でサポートされています。



== コスト

このサービスはBlueXPで無料でご利用いただけます。



== Cloud Analyzer とBlueXPの連携

Cloud Analyzer とBlueXPとの統合は、以下のように機能します。

. [拡張機能]>[クラウド運用]*をクリックして、AWS管理アカウントに接続します。
. ネットアップでは、お客様の環境を次のように設定し
+
.. Spot プラットフォームで組織を作成します。
.. お客様を歓迎する E メールを Spot に送信します。
+
BlueXPで使用するのと同じシングルサインオンの資格情報を使用して、Spotサービスにログインできます。

.. Cloud Analyzer が AWS アカウントデータの処理を開始します。


. BlueXPでは、クラウド運用ページが更新され、その情報を使用して過去、現在、将来のクラウドコストに関する分析情報を得ることができます。
. 任意のタイミングで [* Get Full Analysis] をクリックすると、 Spot の Cloud Analyzer が表示され、クラウド関連の支出と削減効果を詳細に分析できます。




== データセキュリティ

Cloud Analyzer データは保存中に暗号化され、どのアカウントのクレデンシャルも保存されません。
